name: find-codeowners-action
description: Find the owners from CODEOWNERS

inputs:
  codeowners:
    description: Filename of CODEOWNERS
    required: true
  find-by-path:
    description: Path to find the owners
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
