name: find-codeowners-action
description: Find the owners from CODEOWNERS

inputs:
  filename:
    description: Filename to find the owners
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
