name: find-codeowners-action
description: Find the owners from CODEOWNERS

inputs:
  codeowners:
    description: Path of CODEOWNERS
    required: true
  path:
    description: Path(s) to find the owners (multiline)
    required: true
  path-glob:
    description: If true, evaluate path as glob pattern(s)
    default: false

outputs:
  owners:
    description: List of owners, separated by space
  owners-without-organization:
    description: List of owners in the form of @user or @team, separated by space
  orphan-files:
    description: List of files which are not owned in CODEOWNERS, separated by new line

runs:
  using: 'node20'
  main: 'dist/index.js'
